
name: update

on:
  push:
    branches:
      - master
    paths:
      - 'coordinates/**'
      - 'PDFs/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get working copy
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build the application
        run: |
          ./build_me.sh
      - name: Run the application
        run: |
          ./run_me.sh
      - name: Publish calendar files
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add CSVs
          git add ICSs
          git commit -am "Update dynamic content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
